"""
Skill system for Mythos.

Skills are mini-plugins that extend Mythos with new capabilities.
Each skill has a manifest.yaml (metadata) and a skill.py (handler code).

Three sources:
  1. Pre-installed: shipped with Mythos in skills/ directory
  2. Marketplace: installable from a remote GitHub-based index
  3. AI-created: generated by the model on-the-fly, stored locally,
     marked private (never shared to marketplace)

Skill storage:
  Pre-installed: <package_root>/skills/<name>/
  Installed:     ~/.config/mythos/skills/<name>/
  AI-created:    ~/.config/mythos/skills/custom/<name>/
"""

from __future__ import annotations

import importlib.util
import json
import logging
import os
import shutil
import sys
import time
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

import yaml

from mythos_cli.config_store import PACKAGE_ROOT, mythos_home

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Skill data classes
# ---------------------------------------------------------------------------

class SkillCommand:
    """One command exposed by a skill."""

    def __init__(self, name: str, description: str, handler_fn: str):
        self.name = name
        self.description = description
        self.handler_fn = handler_fn  # function name in skill.py


class Skill:
    """A loaded skill with metadata and callable handlers."""

    def __init__(
        self,
        name: str,
        version: str,
        description: str,
        author: str,
        commands: List[SkillCommand],
        skill_dir: Path,
        source: str = "preinstalled",  # preinstalled | marketplace | custom
        tags: Optional[List[str]] = None,
        homepage: str = "",
    ):
        self.name = name
        self.version = version
        self.description = description
        self.author = author
        self.commands = commands
        self.skill_dir = skill_dir
        self.source = source
        self.tags = tags or []
        self.homepage = homepage
        self._module: Optional[Any] = None

    @property
    def manifest_path(self) -> Path:
        return self.skill_dir / "manifest.yaml"

    @property
    def script_path(self) -> Path:
        return self.skill_dir / "skill.py"

    def _load_module(self) -> Any:
        """Dynamically load skill.py from the skill directory."""
        if self._module is not None:
            return self._module
        script = self.script_path
        if not script.exists():
            raise FileNotFoundError(f"skill.py not found for skill '{self.name}' at {script}")
        spec = importlib.util.spec_from_file_location(
            f"mythos_skill_{self.name}", str(script)
        )
        if spec is None or spec.loader is None:
            raise ImportError(f"Cannot create module spec for {script}")
        mod = importlib.util.module_from_spec(spec)
        # Sandboxed: do NOT add to sys.modules permanently
        try:
            spec.loader.exec_module(mod)
        except Exception as e:
            raise ImportError(f"Error loading skill '{self.name}': {e}")
        self._module = mod
        return mod

    def run(self, command_name: str, args: str, context: Optional[Dict] = None) -> str:
        """Execute a skill command. Returns the output string."""
        mod = self._load_module()
        # Find the command
        cmd = None
        for c in self.commands:
            if c.name == command_name:
                cmd = c
                break
        if cmd is None:
            available = ", ".join(c.name for c in self.commands)
            raise ValueError(
                f"Unknown command '{command_name}' for skill '{self.name}'. "
                f"Available: {available}"
            )
        handler = getattr(mod, cmd.handler_fn, None)
        if handler is None:
            raise AttributeError(
                f"Skill '{self.name}' has no function '{cmd.handler_fn}' in skill.py"
            )
        ctx = context or {}
        result = handler(args, ctx)
        if not isinstance(result, str):
            result = str(result)
        return result

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "version": self.version,
            "description": self.description,
            "author": self.author,
            "source": self.source,
            "tags": self.tags,
            "homepage": self.homepage,
            "commands": [
                {"name": c.name, "description": c.description}
                for c in self.commands
            ],
            "dir": str(self.skill_dir),
        }


# ---------------------------------------------------------------------------
# Manifest parsing
# ---------------------------------------------------------------------------

def _parse_manifest(skill_dir: Path, source: str = "preinstalled") -> Skill:
    """Parse a manifest.yaml and return a Skill object."""
    manifest_path = skill_dir / "manifest.yaml"
    if not manifest_path.exists():
        raise FileNotFoundError(f"No manifest.yaml in {skill_dir}")
    with open(manifest_path, "r") as f:
        data = yaml.safe_load(f) or {}
    name = data.get("name", skill_dir.name)
    version = str(data.get("version", "1.0.0"))
    description = data.get("description", "")
    author = data.get("author", "unknown")
    tags = data.get("tags", [])
    homepage = data.get("homepage", "")
    commands = []
    for cmd_data in data.get("commands", []):
        commands.append(SkillCommand(
            name=cmd_data.get("name", "run"),
            description=cmd_data.get("description", ""),
            handler_fn=cmd_data.get("handler", "run"),
        ))
    return Skill(
        name=name,
        version=version,
        description=description,
        author=author,
        commands=commands,
        skill_dir=skill_dir,
        source=source,
        tags=tags,
        homepage=homepage,
    )


# ---------------------------------------------------------------------------
# SkillManager
# ---------------------------------------------------------------------------

class SkillManager:
    """
    Central manager for the Mythos skill system.

    Discovers, loads, runs, installs, uninstalls, and creates skills.
    """

    def __init__(self, config: Optional[Dict] = None):
        self.config = config or {}
        self._skills: Dict[str, Skill] = {}  # name -> Skill
        self._loaded = False

    # -- paths ---------------------------------------------------------------

    @staticmethod
    def preinstalled_dir() -> Path:
        return PACKAGE_ROOT / "skills"

    @staticmethod
    def installed_dir() -> Path:
        return mythos_home() / "skills"

    @staticmethod
    def custom_dir() -> Path:
        return mythos_home() / "skills" / "custom"

    # -- discovery -----------------------------------------------------------

    def discover(self) -> None:
        """Scan all skill directories and load manifests."""
        self._skills.clear()

        # 1. Pre-installed skills (shipped with Mythos)
        pre_dir = self.preinstalled_dir()
        if pre_dir.is_dir():
            for child in sorted(pre_dir.iterdir()):
                if child.is_dir() and (child / "manifest.yaml").exists():
                    try:
                        skill = _parse_manifest(child, source="preinstalled")
                        self._skills[skill.name] = skill
                    except Exception as e:
                        logger.warning("Failed to load pre-installed skill %s: %s", child.name, e)

        # 2. Marketplace-installed skills
        inst_dir = self.installed_dir()
        if inst_dir.is_dir():
            for child in sorted(inst_dir.iterdir()):
                if child.name == "custom":
                    continue  # handled below
                if child.is_dir() and (child / "manifest.yaml").exists():
                    try:
                        skill = _parse_manifest(child, source="marketplace")
                        if skill.name not in self._skills:
                            self._skills[skill.name] = skill
                    except Exception as e:
                        logger.warning("Failed to load installed skill %s: %s", child.name, e)

        # 3. AI-created custom skills
        cust_dir = self.custom_dir()
        if cust_dir.is_dir():
            for child in sorted(cust_dir.iterdir()):
                if child.is_dir() and (child / "manifest.yaml").exists():
                    try:
                        skill = _parse_manifest(child, source="custom")
                        if skill.name not in self._skills:
                            self._skills[skill.name] = skill
                    except Exception as e:
                        logger.warning("Failed to load custom skill %s: %s", child.name, e)

        self._loaded = True

    def _ensure_loaded(self) -> None:
        if not self._loaded:
            self.discover()

    # -- query ---------------------------------------------------------------

    def list_skills(self, source: Optional[str] = None) -> List[Skill]:
        """Return all loaded skills, optionally filtered by source."""
        self._ensure_loaded()
        skills = list(self._skills.values())
        if source:
            skills = [s for s in skills if s.source == source]
        return skills

    def get_skill(self, name: str) -> Optional[Skill]:
        """Get a skill by name."""
        self._ensure_loaded()
        return self._skills.get(name)

    def get_all_commands(self) -> List[Tuple[str, SkillCommand]]:
        """Return (skill_name, SkillCommand) for every command across all skills."""
        self._ensure_loaded()
        result = []
        for skill in self._skills.values():
            for cmd in skill.commands:
                result.append((skill.name, cmd))
        return result

    # -- execution -----------------------------------------------------------

    def run_skill(self, skill_name: str, command_name: str, args: str = "",
                  context: Optional[Dict] = None) -> str:
        """Run a skill command and return the output."""
        self._ensure_loaded()
        skill = self._skills.get(skill_name)
        if skill is None:
            available = ", ".join(self._skills.keys())
            raise ValueError(f"Skill '{skill_name}' not found. Available: {available}")
        return skill.run(command_name, args, context)

    def run_command(self, command_name: str, args: str = "",
                    context: Optional[Dict] = None) -> str:
        """
        Run a command by its short name. If multiple skills expose
        the same command name, the first match wins.
        """
        self._ensure_loaded()
        for skill in self._skills.values():
            for cmd in skill.commands:
                if cmd.name == command_name:
                    return skill.run(command_name, args, context)
        raise ValueError(f"No skill command '{command_name}' found.")

    # -- install / uninstall -------------------------------------------------

    def install_skill(self, skill_dir: Path) -> Skill:
        """
        Install a skill from a local directory into ~/.config/mythos/skills/.
        """
        dest = self.installed_dir() / skill_dir.name
        if dest.exists():
            shutil.rmtree(dest)
        self.installed_dir().mkdir(parents=True, exist_ok=True)
        shutil.copytree(skill_dir, dest)
        skill = _parse_manifest(dest, source="marketplace")
        self._skills[skill.name] = skill
        return skill

    def install_from_manifest_data(self, name: str, manifest_yaml: str,
                                   skill_py: str) -> Skill:
        """
        Install a skill from raw YAML/Python content (used by marketplace).
        """
        # Sanitize skill name to prevent path traversal
        safe_name = name.lower().replace(" ", "_").replace("-", "_")
        safe_name = "".join(c for c in safe_name if c.isalnum() or c == "_")
        if not safe_name:
            raise ValueError("Invalid skill name for install")
        dest = self.installed_dir() / safe_name
        dest.mkdir(parents=True, exist_ok=True)
        (dest / "manifest.yaml").write_text(manifest_yaml)
        (dest / "skill.py").write_text(skill_py)
        skill = _parse_manifest(dest, source="marketplace")
        self._skills[skill.name] = skill
        return skill

    def uninstall_skill(self, name: str) -> bool:
        """Remove an installed or custom skill. Pre-installed skills cannot be removed."""
        skill = self._skills.get(name)
        if skill is None:
            return False
        if skill.source == "preinstalled":
            raise ValueError(f"Cannot uninstall pre-installed skill '{name}'")
        if skill.skill_dir.exists():
            shutil.rmtree(skill.skill_dir)
        del self._skills[name]
        return True

    # -- AI skill creation ---------------------------------------------------

    def create_custom_skill(self, name: str, manifest_yaml: str,
                            skill_py: str) -> Skill:
        """
        Create an AI-generated custom skill. Saved to
        ~/.config/mythos/skills/custom/<name>/.
        """
        safe_name = name.lower().replace(" ", "_").replace("-", "_")
        # Only allow alphanumeric + underscore
        safe_name = "".join(c for c in safe_name if c.isalnum() or c == "_")
        if not safe_name:
            raise ValueError("Invalid skill name")
        dest = self.custom_dir() / safe_name
        dest.mkdir(parents=True, exist_ok=True)
        (dest / "manifest.yaml").write_text(manifest_yaml)
        (dest / "skill.py").write_text(skill_py)
        skill = _parse_manifest(dest, source="custom")
        self._skills[skill.name] = skill
        return skill

    # -- AI skill creation prompt --------------------------------------------

    @staticmethod
    def build_create_prompt(user_description: str) -> str:
        """
        Build a system prompt that instructs the AI to generate a new skill.
        The AI should respond with two fenced code blocks:
          ```yaml (manifest)
          ```python (skill code)
        """
        return f"""You are a Mythos skill creator. The user wants a new skill described as:

"{user_description}"

Create the skill by producing TWO fenced code blocks:

1. A ```yaml block containing the manifest.yaml with these fields:
   - name: short lowercase skill name (underscores ok)
   - version: "1.0.0"
   - description: one-line description
   - author: "mythos-ai"
   - tags: list of relevant tags
   - commands: list of command objects, each with:
     - name: the command name (e.g. "run", "ask", "generate")
     - description: what this command does
     - handler: the Python function name that implements it

2. A ```python block containing the skill.py code:
   - Each handler function must accept (args: str, context: dict) and return a str
   - The context dict may contain: "engine" (inference engine), "memory" (conversation memory), "config" (dict), "messages" (list of recent messages)
   - Use only Python stdlib + yaml (already available)
   - Keep it focused and functional
   - Do NOT import or use subprocess, os.system, eval, exec, or any dangerous operations
   - Do NOT access the filesystem outside of reading context data
   - The skill must be safe to run

Respond with ONLY the two code blocks, no other text."""

    @staticmethod
    def parse_create_response(response: str) -> Tuple[str, str]:
        """
        Parse the AI response to extract manifest.yaml and skill.py content.
        Returns (manifest_content, skill_content).
        """
        manifest = ""
        skill_code = ""

        # Extract yaml block
        yaml_match = _extract_fenced_block(response, "yaml")
        if not yaml_match:
            yaml_match = _extract_fenced_block(response, "yml")
        if yaml_match:
            manifest = yaml_match

        # Extract python block
        py_match = _extract_fenced_block(response, "python")
        if not py_match:
            py_match = _extract_fenced_block(response, "py")
        if py_match:
            skill_code = py_match

        if not manifest or not skill_code:
            raise ValueError(
                "Could not parse skill from AI response. "
                "Expected ```yaml and ```python code blocks."
            )
        return manifest, skill_code

    # -- marketplace listing cache -------------------------------------------

    def marketplace_cache_path(self) -> Path:
        return mythos_home() / "skills" / ".marketplace_cache.json"

    def load_marketplace_cache(self) -> List[Dict]:
        """Load cached marketplace listings."""
        cache = self.marketplace_cache_path()
        if cache.exists():
            try:
                data = json.loads(cache.read_text())
                if time.time() - data.get("fetched_at", 0) < 3600:
                    return data.get("skills", [])
            except Exception:
                pass
        return []

    def save_marketplace_cache(self, skills: List[Dict]) -> None:
        """Save marketplace listings to cache."""
        cache = self.marketplace_cache_path()
        cache.parent.mkdir(parents=True, exist_ok=True)
        cache.write_text(json.dumps({
            "fetched_at": time.time(),
            "skills": skills,
        }))


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _extract_fenced_block(text: str, lang: str) -> Optional[str]:
    """Extract content from a fenced code block with the given language tag."""
    import re
    pattern = rf"```{lang}\s*\n(.*?)```"
    match = re.search(pattern, text, re.DOTALL)
    if match:
        return match.group(1).strip()
    # Try without language tag
    pattern2 = r"```\s*\n(.*?)```"
    matches = re.findall(pattern2, text, re.DOTALL)
    if matches:
        return matches[0].strip()
    return None
